package br.ufpe.cin.erbotool.tools;

public enum SmartSmellEnum {

	BRAIN_METHOD,
	ClASS_DATA_SHOULD_BE_PRIVATE,
	COMPLEX_CONDITION,
	COMPLEX_METHOD,
	CYCLE,
	DATA_CLASS,
	DEAD_CODE,
	FEATURE_ENVY,
	GOD_CLASS,
	LARGE_CLASS,
	LONG_METHOD,
	LONG_PARAM,
	MESSAGE_CHAIN,
	MIDDLE_MAN,
	NESTED_BLOCK_DEPTH,
	REFUSED_PARENT_BEQUEST,
	SHOTGUN_SURGERY,
	STATE_CHECKING,
	TRADITION_BREAKER,
	UNKNOWN;
	
}
