package br.ufpe.cin.erbotool.util.enums;

public enum PropertiesEnum {

	GITHUB_PROJECT_LIST,
	REPO_DIR,
	GIT_APP,
	GIT_TAG_SCRIPT,
	JAVA_APP,
	MAIN_DIR,
	REFACTORINGMINER_BIN,
	REFACTORINGMINER_PARAMETERS,
	SMARTSMELL_JAR,
	SMARTSMELL_PARAMETERS,
	ADOCTOR_JAR,
	ADOCTOR_SMELLS,
	ADOCTOR_PARAMETERS,
	ADOCTOR_OUTPUT,
	JAR_EXTENSION
}
